### ISSUE TITLE
Erro ao carregar a imagem

### ISSUE THREAD

**Issue by danielsousa8** [raquel-maia/nordestinadigital#1]
Falta colocar o ponto "." antes do path da imagem e colocar a letra **A** minúscula "avatar".
https://github.com/raquel-maia/rocketseat/blob/51261193b0096ff38ae7dde73ae34fb4a125789d/index.html#L19

![Screenshot (89)](https://user-images.githubusercontent.com/5693912/210659651-961d899f-7dfe-46d1-882c-47f6abc543c9.png)

**Comment by raquel-maia** [comment]
Obrigada, Daniel! Ajustei esse erro.
